### ISSUE TITLE
Can't run collect_dataset.py

### ISSUE THREAD

**Issue by jkutaso** [AlignmentResearch/learned-planner#2]
I am trying to use collect_dataset.py to recreate the dataset that is studied in this paper. I'm running it using these arguments and getting the following error:

`python learned_planner/interp/collect_dataset.py -m /root/.cache/huggingface/hub/models--AlignmentResearch--learned-planner/snapshots/91e6ac18fb3720dee02f22337113db5a15e28e22/drc33/bkynosqi/cp_2002944000 -t -e`

```
/opt/venv/lib/python3.10/site-packages/wandb/analytics/sentry.py:90: SentryHubDeprecationWarning: `sentry_sdk.Hub` is deprecated and will be removed in a future major release. Please consult our 1.x to 2.x migration guide for details on how to migrate `Hub` usage to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
  self.hub = sentry_sdk.Hub(client)
Device: cpu
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
Traceback (most recent call last):
  File "/workspace/learned_planner/interp/collect_dataset.py", line 523, in <module>
    collect_dataset(model_path, args)
  File "/workspace/learned_planner/interp/collect_dataset.py", line 489, in collect_dataset
    cfg, policy = load_jax_model_to_torch(model_path, eval_env)
  File "/workspace/learned_planner/interp/utils.py", line 125, in load_jax_model_to_torch
    _, _, args, state, _ = cleanba_impala.load_train_state(path, vec_env)
  File "/opt/venv/lib/python3.10/site-packages/cleanba/cleanba_impala.py", line 781, in load_train_state
    policy, carry, params = args.net.init_params(env, jax.random.PRNGKey(1234))
  File "/opt/venv/lib/python3.10/site-packages/cleanba/network.py", line 55, in init_params
    policy = Policy(n_actions_from_envs(envs), self)
  File "/opt/venv/lib/python3.10/site-packages/cleanba/network.py", line 88, in n_actions_from_envs
    action_space = envs.single_action_space
AttributeError: 'EnvpoolVecEnv' object has no attribute 'single_action_space'
```

Am I doing something wrong or is this not the expected behavior here? Any suggestions for a fix? I got the path from using the example code and printing out MODEL_PATH

**Comment by taufeeque9** [comment]
This issue is fixed with the latest PR. Please open it again if you encounter it again.
